### PR TITLE
CCITTFaxDecoderStream Update

### PR DESCRIPTION
**Pull request by Schmidor**
I want to propose the following update of the CCITT decoder.

We had a few fixes since the version from 2016. Futher I later helped to use the decoder in ICEpdf and did some changes for the EncodedByteAlign-Flag.

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Hi Schmidor,

unless I am mistaken the pdfbox committers do not monitor pull requests. 

Better post on the mailing list or to create a Jira issue to ensure that they are aware of your proposal.

**Comment by THausherr** [comment]
Thanks, I've now found this PR and attached it to
https://issues.apache.org/jira/browse/PDFBOX-5057

**Comment by THausherr** [comment]
Thank you for taking the time to merge your changes into our code!

**Comment by THausherr** [comment]
I made some additional changes based on the Sonar report
- check the length of the read bytes. I'm wondering whether it might happen that a valid image has less than 20 bytes, but for now I'll just assume so
- "& 0xff" when using streamData[1] to avoid "int promotion"

**Comment by THausherr** [comment]
> I'm wondering whether it might happen that a valid image has less than 20 bytes, but for now I'll just assume so

It turns out, I hit one that is 19 bytes long.

**Pull request closed without merging**
