### PR TITLE
Merge alternate OpenType Advanced Typographic Table (ATT) support.

### PR DESCRIPTION
**Pull request by skynavga**

### CODE REVIEW

**Comment by skynavga** [comment]
Please ignore.

**Comment by lehmi** [comment]
Is this some work in progress?

**Comment by skynavga** [comment]
Sorry, created PR against wrong branch. It was intended for non-apache fork only, skynav/pdfbox.

**Comment by lehmi** [comment]
Hmm, it's a pity. Looks interesting. Is there chance to merge it into pdfbox sometime in the future?

**Comment by skynavga** [comment]
Yes, it is possible. There is some overlap with the limited ATT support that has already been added to fontbox, i.e., GlyphSubsitutionTable, so that would have to be worked out. My implementation is already being used in https://github.com/apache/xmlgraphics-fop/tree/trunk/fop-core/src/main/java/org/apache/fop/complexscripts and in https://github.com/skynav/ttt/tree/master/ttt-ttpe.

**Comment by lehmi** [comment]
Cool, good to know. I put this on my TODO list. Thanks!

**Pull request closed without merging**
