### PR TITLE
Fixed some README issues

### PR DESCRIPTION
**Pull request by SaptarshiSarkar12**
I have fixed some problems in Readme file, by adding code blocks and direct link to LICENSE.txt for better navigation and accessibility.

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
@THausherr Please review this Pull Request.

**Comment by THausherr** [comment]
Thanks, fixed.

**Comment by SaptarshiSarkar12** [comment]
> Thanks, fixed.

Welcome @THausherr

**Comment by SaptarshiSarkar12** [comment]
@THausherr Please let me know why pull requests are not accepted.

**Comment by THausherr** [comment]
Your changes were accepted. PRs aren't merged directly because this is a read-only mirror to an svn repository. The "official" road is to create a JIRA ticket and to attach a patch. But we do read PRs. If you want to create a JIRA ticket and aren't a user, please create an account at https://selfserve.apache.org/jira-account.html (write something so that we know it's you and not some spammer with a generic text)

**Comment by SaptarshiSarkar12** [comment]
Okay I understood. Thank you for explaining me @THausherr !

**Pull request closed without merging**
