### PR TITLE
Fix Travis Build

### PR DESCRIPTION
**Pull request by PascalSchumacher**
Remove Open JDK 7, because Travis no longer supports.

Replace Oracle JDK 8 with Open JDK 8, because Travis no longer supports Oracle JDK 8.

### CODE REVIEW

**Comment by THausherr** [comment]
Where can one see the list of currently supported JDKs?

**Comment by PascalSchumacher** [comment]
https://docs.travis-ci.com/user/reference/xenial/#jvm-clojure-groovy-java-scala-support lists the pre-installed JVMs (of the default build environment xenial): openjdk8, openjdk10, and openjdk11 

Travis uses https://github.com/sormuras/bach#install-jdksh to install further jdks, currently available are (at least): openjdk12, openjdk13, openjdk14, openjdk-ea

**Comment by THausherr** [comment]
I've just made a commit that still includes oracle jdks, see 
https://docs.travis-ci.com/user/languages/java#testing-against-multiple-jdks
and your URL also mentions oracle so I'm somewhat confused. Could you please accept the change to see whether it builds on github? If it doesn't then I'll remove oracle.

**Comment by PascalSchumacher** [comment]
https://docs.travis-ci.com/user/languages/java#testing-against-multiple-jdks is out of date. Oracle JDK was removed a short time ago.

https://travis-ci.org/apache/pdfbox/builds/574443646 shows that the build on oraclejkd8 failed after you commited your change to trunk.

**Comment by THausherr** [comment]
Thanks, I'm trying with oraclejdk12, the error message is "Expected feature release number in range of 9 to 14, but got: 8", please merge that one.

**Comment by PascalSchumacher** [comment]
It works: https://travis-ci.org/apache/pdfbox/builds/574482630

Trunk is also green now: https://travis-ci.org/apache/pdfbox/builds/574481781

Thank you very much!

**Comment by THausherr** [comment]
OK great! Feel free to ping us again when needed, on the users mailing list or in JIRA. Note that this here on github is a read only repository and we're not notified of PRs. This was pure chance that I looked here.

**Comment by PascalSchumacher** [comment]
I wasn't aware that there are no notifications.  Thanks for letting me know. I will use Jira or the mailing list next time.

I am not sure if is a good idea to add oraclejdk12. Patches for it will end next months (see: https://www.oracle.com/technetwork/java/java-se-support-roadmap.html) so it could very well be removed in a few weeks.

**Comment by THausherr** [comment]
I'll replace it with 13 when it happens. Maybe put 11 there too, assuming that is the long term version.

**Pull request closed without merging**
