### PR TITLE
 downgrade maven-bundle-plugin to version 3.2.0 to fix build on travis

### PR DESCRIPTION
**Pull request by PascalSchumacher**
(workaround for travis-ci/travis-ci#7517)

### CODE REVIEW

**Comment by THausherr** [comment]
This is a read only repository. Please close it and create a request in [JIRA](https://issues.apache.org/jira/browse/PDFBOX) and add a diff or explain what you need.

**Comment by PascalSchumacher** [comment]
Sorry, I have updated the title and the description.

By the way: Even read-only non-git repositories by can merge pull requests by:

1. Convert the pull request to a patch by appending `.patch` to the pull request URL e.g. https://github.com/apache/pdfbox/pull/37.patch
2. Close the pull request adding `closes #pull-request-number` to a commit message (e.g. `closes #37`).

Of course I can create a jira issue for this, but I thought demonstrating with a pull request that this change fixes the pdf-box build on travis to be more effective.

**Comment by THausherr** [comment]
Yes you should still create a JIRA issue. Every commit is related to a JIRA issue, never to a github issue.

**Comment by lehmi** [comment]
Am 05.05.2017 um 10:42 schrieb Tilman Hausherr:
> Yes you should still create a JIRA issue. Every commit is related to a JIRA 
> issue, never to a github issue.

The issue should be solved. The maven guys did some magic with the repository. 
So, no need to downgrade the version of the plugin.

Andreas

**Pull request closed without merging**
